// Custom shader file for gm_construct.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

gm_construct/EC8FFB75C49F146B322860C4697E445A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/BDB5BD263FBA1DD6A201C11535636AB4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/16A108AC1B72A8DD66E2D05B6A9BB2C5
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/4F1CE12FC04CACDF97E9BC9C437D26D1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/503F39E4466D471B01D1438F397A9AA3
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010g.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/36FC73C5913DA9C5527C21C5521FAFBD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010g.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/977A02E9014950ADE99CB3240DF432A4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007m.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/37ED866B50DA1178ADDDDD1812F37132
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007m.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/61FE6412ACFB8D1F83BC34EDB5E9E6B0
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3D49EEA0D203E924BF14CCFD2BA2DC10
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/AEF36852FDDAC166C858559B171033FD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B6D19746658E7DF47FDEFD4FA735D935
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E683446E5DBC02ABDA5EB4EAAD58D0BD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7B032EB8A6AC0C2CFC97A95F6A66AB82
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/18F7D5D1055B9802FBF908089EC5654B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/skip.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1F1BD78F9A05376F4245AE904EBA2FBC
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/skip.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EE908ECDD92C142C70C1FA8E8DD6AD8E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall003a_construct.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A876868EB6DA4F6ED4B12E36AC22C485
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E5CE7C0616AA8ECEAB824AC5D1B9BF93
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0850773E9C9320E9A892932E8B519F6E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/06796FE8CCA889FEF02203A28E0DA861
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1673815AE3AEC7D6BCC91F2C30807B21
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D354E617625FDB79EF59C8D995EA0D98
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/535141C7E9C95CD0B5B507953C959974
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/02F6776FCEBEE742107364873AF641C1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/5C0D2B51F86F93407E01DE7E2408A4D2
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B34476E71E6AE7381DE7FD12948BFBCD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/CA2632B2FF62D081D006CD48A3BECC06
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B2D40E47869CB274313ADBE45EF8E623
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/C764057EB1557DCB689AAF1F6C97E238
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/AD79223C381A832E9B8FA833C4A7CF0E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/C0C2C69EB657C9122697D3983A06BF48
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2A28A0D0ACABBB82429225FDA12730E3
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/CF8D8EE9A83C0C0D081D0FCBF9EEEA71
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/24A4BFDF000E283A3B5E0D50AC9FC4D4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/5476DAF5D71FA16D78160060386CF091
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1A1448C98E2A2CC39CCF3617ABB14793
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/79EA48F6C42790ECB62054CB15CA0B28
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E0CD134421E490361D5284EDDBF1E342
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/146BAB198D9CC59192B226959C3BC8E5
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FB47F56818EF963BB402668882F42A36
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/61419D8CE36CC334D9DD5A4CC55867E1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A2DB0E871C750212602AD841C5B66867
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/BACAC2F44EC100AAAAA1931028179075
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/58CCDFEB3DDC729D2E27E94C2C6EA428
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/4F57EA4ECA344ED4A87F689E90AF7B74
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1C234E8D9E7F16032B05D8C8FCAD4160
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/dev/dev_measuregeneric01b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/449E9225ECDECD97BC951DB4DC00D7EA
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/plasticceiling002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1F6F5AA690B5A704113E34B4A76E7D90
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/plasticceiling002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/6BCF46A4E96F7C1C3E95FFECE59F3F07
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0596891F20382DA7470948D70965CB0E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor008a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/01081BC3385246418D4759E9FA597040
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/ACFB524711E334F509A825D88C8B06AD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D53A88A81E384E0D1B104377194C4AB1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/6CC99E04DA5D5BC7501D0FE62A86FCCB
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/039AD397345E76F6FC955B4A8CA6CC41
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2754A6632B341D9AA24A30DA3E56998E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3C91EBB328EE2CB581C6E10C1405F14E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A900BB59D452F5064CE1E233CBE9E9C1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/DD11A04DFB315E40F2A29F0748E52195
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7ECA553794706E678DF27988AB62AB77
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3474E5A557E9F443F8130F27462B97E4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0D5F55419B91F232F08E86DEBE93BA9F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3FB7F5D567A5896F585B6137CED71359
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1E2D8E7F86B3BF0470F279766B308595
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A2DC7D7593D88515A9197DE5B1004355
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0831362ACDB58358BDA58AFFBBF7657E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/F8B1115FC6B042F7C60CB3A1077E1C27
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/AD66F6F996D51EB8403918930075E845
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0DCAB90A1C1C5F6FC206C524489A8479
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling005a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/26C2A41428E001A4DDA4315C0EEAD53F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007l.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2A909E3CA4267A1F4F7216B483783939
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007l.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3C96980058E003E213F1EE5900AE8C39
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/86ECCF8044E6D3DC439EE206E5711370
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9881F82770662F75B7BE404E50AF6DCA
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007i.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/78C714F824513CF9AAB68CD7F8C772C1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007i.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2B31174E62A19DCCA190CA7F6A9C88C4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A5E0E157D7AD0F483A9F259BA9D8050F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/386DB057DB7734C5283875363CF8BF72
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template006b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D2B55A124B9A4CBE9EE2D1C5FE610A91
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A92626E81EA7EA1740BA8F28FF5CD380
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D4B6A631DEE8A17E37BD7078D9B5672C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3FBBC26B9625FCBDDEFFB6DD7DE60A98
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9A849E87E64F77FB81D12FE4028AB87C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8BBFE8B2BC97432FE0308B01324A6AC3
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/365D4A89ADC53E9F8E6691E18F714D45
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/metalcrate002d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2616307ED2B4163B459B74AA303B143B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8477BE4E8BE767F1322048732BB1C052
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A6BF6396DC1855B28E6FEE3F710171CF
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretestair005a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E6CB5EF1DC00115FD953F07A2AA336C8
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_credits.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FF2193BEC50D31D096D848C321002755
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall053e.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/283F808EA58715BF514B739A8167E59B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013m.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8FA7626AA80CFF780CD5B7A4D41B8852
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/color_room.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/72A13E3FAF70342F98325283719D8800
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/color_room.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D321F482AB454885A87918C8E3B22662
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/flares/twilightflare.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/28F69F0F7CA1CA1C788B6D44B1348B2E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/doorbutton002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

