sbc_opt1	"---"
sbc_opt2	"---"
sbc_opt3	"---"
sbc_opt4	"---"
sbc_string	"play %s"
sbc_ext		"wav"
sbc_folder	""
sbc_tabname	"Sounds:"
sbc_btn		"Play:"
sbc_error	"No sounds"
sbc_arg0	"0"
sbc_arg1	"1"
sbc_arg2	"2"
sbc_arg3	"3"
sbc_arg4	"4"