set toolgun_tool 6
set toolgun_toolcmd1 "vstr toolcmd_modify"
set toolgun_toolcmd2 "vstr toolcmd_modify2"
set toolgun_toolcmd3 "vstr toolcmd_modify3"
set toolgun_toolcmd4 "vstr toolcmd_modify4"
set toolgun_tooltext "Collision"
set toolgun_tooltip1 "Toggles object collision"
set toolgun_tooltip2 " "
set toolgun_tooltip3 " "
set toolgun_tooltip4 "Click E button to change mode"
set toolgun_toolmode1 "Enable"
set toolgun_toolmode2 "Disable"
set toolgun_toolmode3 " "
set toolgun_toolmode4 " "
set toolgun_toolset1 "--------:"
set toolgun_toolset2 "--------:"
set toolgun_toolset3 "--------:"
set toolgun_toolset4 "--------:"
set toolgun_toolset5 "--------:"
set toolgun_toolset6 "--------:"
set toolgun_toolset7 "--------:"
set toolgun_toolset8 "--------:"
set toolgun_toolset9 "--------:"
set toolgun_toolset10 "--------:"
set toolgun_toolset11 "--------:"
set toolgun_toolset12 "--------:"
set toolgun_toolset13 "--------:"
set toolgun_toolset14 "--------:"
set toolgun_toolset15 "--------:"
set toolgun_toolset16 "--------:"
set toolgun_toolset17 "--------:"
set toolgun_toolset18 "--------:"
set toolgun_disabledarg1 "0"
set toolgun_disabledarg2 "0"
set toolgun_disabledarg3 "0"
set toolgun_disabledarg4 "0"
set uitoolmode toggle toolgun_mod19 0 1
set tool_modifypreset "set toolcmd_modify tm %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s 0"
set tool_modifypreset2 "set toolcmd_modify2 tm %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s 1"
set tool_modifypreset3 "set toolcmd_modify3 tm %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s 2"
set tool_modifypreset4 "set toolcmd_modify4 tm %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s 3"
weapon 16