set toolgun_tool 0
set toolgun_toolcmd1 "vstr toolcmd_spawn"
set toolgun_toolcmd2 "vstr toolcmd_spawn"
set toolgun_toolcmd3 "vstr toolcmd_spawn"
set toolgun_toolcmd4 "vstr toolcmd_spawn"
set toolgun_tooltext "Create"
set toolgun_tooltip1 "Creates an object"
set toolgun_tooltip2 " "
set toolgun_tooltip3 " "
set toolgun_tooltip4 " "
set toolgun_toolmode1 " "
set toolgun_toolmode2 " "
set toolgun_toolmode3 " "
set toolgun_toolmode4 " "
set toolgun_toolset1 "--------:"
set toolgun_toolset2 "--------:"
set toolgun_toolset3 "--------:"
set toolgun_toolset4 "--------:"
set toolgun_toolset5 "--------:"
set toolgun_toolset6 "--------:"
set toolgun_toolset7 "--------:"
set toolgun_toolset8 "--------:"
set toolgun_toolset9 "--------:"
set toolgun_toolset10 "--------:"
set toolgun_toolset11 "--------:"
set toolgun_toolset12 "--------:"
set toolgun_toolset13 "--------:"
set toolgun_toolset14 "--------:"
set toolgun_toolset15 "--------:"
set toolgun_toolset16 "--------:"
set toolgun_toolset17 "--------:"
set toolgun_toolset18 "--------:"
set toolgun_disabledarg1 "0"
set toolgun_disabledarg2 "0"
set toolgun_disabledarg3 "0"
set toolgun_disabledarg4 "0"
set uitoolmode toggle toolgun_mod19 0
set tool_spawnpreset set toolcmd_spawn sl prop %s none %s 25 %s 0 %s 1 0 "none" -1 0 0 0 0 1 1 1 0 0 1 10000 0 1 100 100 120 1 0 1000 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.5
weapon 16